[[redirects]]
  from = "https://jsonmaster.netlify.app/*"
  to = "https://jsonworkspace.mythosh.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
